version: '2'
services:
    themecrawler-app:
        image: themecrawler
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://themecrawler-mysql:3306/themecrawler?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    themecrawler-mysql:
        extends:
            file: mysql.yml
            service: themecrawler-mysql
